export const METHOD_NAME_MAP = {
  algorithm: "Algorithm (with uncertainty on the expression itself)",
  bernoulli: "Bernoulli",
  beta: "Beta",
  binomial: "Binomial",
  buildup_exp: "Exponential build-up",
  buildup_linear: "Linear build-up",
  constant: "Constant",
  decline_exp: "Exponential decline/dropoff",
  decline_linear: "Linear decline/dropoff",
  discount: "Discount",
  exponential: "Exponential",
  function: "Exact Function",
  gamma: "Gamma",
  logistic: "Logistic",
  lognormal: "Lognormal",
  lookup_table: "Look-up table",
  normal: "Normal",
  pareto: "Pareto",
  pert: "Pert",
  rectangle: "Rectangle",
  repeat: "Repeat",
  sumTimeseries: "Sum Timeseries",
  timefunction: "Timefunction",
  timeseries: "Timeseries",
  triangle: "Triangle",
  uniform: "Uniform",
  uniform_discrete: "Discrete Uniform",
}
