export const vars = [
  {
      "module_id": 1,
      "id": 100,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "rig",
      "title": "Rig Cost (USD/day)",
      "type": "riskVariable",
      "value": "0.3 50000 100000 150000"
  },
  {
      "module_id": 1,
      "id": 101,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "wab",
      "title": "Welltec Elements Base Cost (USD)",
      "type": "variable",
      "value": "40000 80000 120000"
  },
  {
      "module_id": 1,
      "id": 102,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "und",
      "title": "Underreaming Base Cost (USD)",
      "type": "variable",
      "value": "500 1000 1500"
  },
  {
      "module_id": 1,
      "id": 103,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "cal",
      "title": "Caliber Log Base Cost (USD)",
      "type": "variable",
      "value": "20000 40000 60000"
  },
  {
      "module_id": 1,
      "id": 104,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "cmt",
      "title": "Primary Cement Base Cost (USD)",
      "type": "variable",
      "value": "125000 250000 375000"
  },
  {
      "module_id": 1,
      "id": 105,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "cbl",
      "title": "Cement Bond Log Base Cost (USD)",
      "type": "variable",
      "value": "20000 40000 60000"
  },
  {
      "module_id": 1,
      "id": 106,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csq",
      "title": "Cement Squeeze Base Cost (USD)",
      "type": "variable",
      "value": "60000 120000 180000"
  },
  {
      "module_id": 1,
      "id": 107,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "cmt2",
      "title": "2nd Stage Cement Base Cost (USD)",
      "type": "variable",
      "value": "125000 250000 375000"
  },
  {
      "module_id": 1,
      "id": 108,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "side",
      "title": "Sidetrack Base Cost (USD)",
      "type": "variable",
      "value": "1000000 2000000 3000000"
  },
  {
      "module_id": 1,
      "id": 109,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "wo",
      "title": "Workover Base Cost (USD)",
      "type": "variable",
      "value": "50000 100000 150000"
  },
  {
      "module_id": 1,
      "id": 110,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "aban",
      "title": "Abandonment Base Cost (USD)",
      "type": "variable",
      "value": "50000 100000 150000"
  },
  {
      "module_id": 2,
      "id": 201,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_wab",
      "title": "Welltec Elements Rig Days",
      "type": "variable",
      "value": "0.1 0.2 0.3"
  },
  {
      "module_id": 2,
      "id": 202,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_und",
      "title": "Underreaming Rig Days",
      "type": "variable",
      "value": "0.25 0.5 0.75"
  },
  {
      "module_id": 2,
      "id": 203,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_cal",
      "title": "Caliber Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 2,
      "id": 204,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_cmt",
      "title": "Primary Cement Rig Days",
      "type": "variable",
      "value": "0.3 0.4 0.5"
  },
  {
      "module_id": 2,
      "id": 205,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_cbl",
      "title": "Cement Bond Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 2,
      "id": 206,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_csq",
      "title": "Cement Squeeze Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 2,
      "id": 207,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_cmt2",
      "title": "2nd Stage Cement Rig Days",
      "type": "variable",
      "value": "0.3 0.4 0.5"
  },
  {
      "module_id": 2,
      "id": 208,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_side",
      "title": "Sidetrack Rig Days",
      "type": "variable",
      "value": "40 80 120"
  },
  {
      "module_id": 2,
      "id": 209,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_wo",
      "title": "Workover Rig Days",
      "type": "variable",
      "value": "5 10 15"
  },
  {
      "module_id": 2,
      "id": 210,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "oph_d_aban",
      "title": "Abandonment Rig Days",
      "type": "variable",
      "value": "1.5 3 4.5"
  },
  {
      "module_id": 2,
      "id": 211,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_wab",
      "title": "Welltec Elements Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 2,
      "id": 212,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_und",
      "title": "Underreaming Probability",
      "type": "variable",
      "value": "0.6"
  },
  {
      "module_id": 2,
      "id": 213,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_cal",
      "title": "Caliber Log Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 2,
      "id": 214,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_cmt",
      "title": "Primary Cement Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 2,
      "id": 215,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_cbl",
      "title": "Cement Bond Log Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 2,
      "id": 216,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_csq",
      "title": "Cement Squeeze Probability",
      "type": "variable",
      "value": ".1"
  },
  {
      "module_id": 2,
      "id": 217,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_cmt2",
      "title": "2nd Stage Cement Probability",
      "type": "variable",
      "value": ".1"
  },
  {
      "module_id": 2,
      "id": 218,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_side",
      "title": "Sidetrack Probability",
      "type": "variable",
      "value": "0"
  },
  {
      "module_id": 2,
      "id": 219,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_wo",
      "title": "Workover Probability",
      "type": "variable",
      "value": ".2"
  },
  {
      "module_id": 2,
      "id": 220,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "oph_x_aban",
      "title": "Abandonment Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 2,
      "id": 221,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_wab",
      "title": "Welltec Elements (USD)",
      "type": "variable",
      "value": "wab+oph_d_wab*rig"
  },
  {
      "module_id": 2,
      "id": 222,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_und",
      "title": "Underreaming (USD)",
      "type": "variable",
      "value": "und+oph_d_und*rig"
  },
  {
      "module_id": 2,
      "id": 223,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_cal",
      "title": "Caliber Log (USD)",
      "type": "variable",
      "value": "cal+oph_d_cal*rig"
  },
  {
      "module_id": 2,
      "id": 224,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_cmt",
      "title": "Primary Cement (USD)",
      "type": "variable",
      "value": "cmt+oph_d_cmt*rig"
  },
  {
      "module_id": 2,
      "id": 225,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_cbl",
      "title": "Cement Bond Log (USD)",
      "type": "variable",
      "value": "cbl+oph_d_cbl*rig"
  },
  {
      "module_id": 2,
      "id": 226,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_csq",
      "title": "Cement Squeeze (USD)",
      "type": "variable",
      "value": "csq+oph_d_csq*rig"
  },
  {
      "module_id": 2,
      "id": 227,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_cmt2",
      "title": "2nd Stage Cement (USD)",
      "type": "variable",
      "value": "cmt2+oph_d_cmt2*rig"
  },
  {
      "module_id": 2,
      "id": 228,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_side",
      "title": "Sidetrack (USD)",
      "type": "variable",
      "value": "side+oph_d_side*rig"
  },
  {
      "module_id": 2,
      "id": 229,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_wo",
      "title": "Workover (USD)",
      "type": "variable",
      "value": "wo+oph_d_wo*rig"
  },
  {
      "module_id": 2,
      "id": 230,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "oph_tot_aban",
      "title": "Abandonment (USD)",
      "type": "variable",
      "value": "aban+oph_d_aban*rig"
  },
  {
      "module_id": 2,
      "id": 250,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ophwab_all",
      "title": "Open Hole Wab (USD)",
      "type": "variable",
      "value": "oph_tot_wab*oph_x_wab+oph_tot_und*oph_x_und+oph_tot_cal*oph_x_cal+oph_tot_cmt*oph_x_cmt+oph_tot_cbl*oph_x_cbl+oph_tot_csq*oph_x_csq+oph_tot_cmt2*oph_x_cmt2+oph_tot_side*oph_x_side+oph_tot_wo*oph_x_wo+oph_tot_aban*oph_x_aban"
  },
  {
      "module_id": 3,
      "id": 301,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_wab",
      "title": "Welltec Elements Rig Days",
      "type": "variable",
      "value": ".1 .2 .3"
  },
  {
      "module_id": 3,
      "id": 302,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_und",
      "title": "Underreaming Rig Days",
      "type": "variable",
      "value": "0.25 0.5 0.75"
  },
  {
      "module_id": 3,
      "id": 303,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_cal",
      "title": "Caliber Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 3,
      "id": 304,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_cmt",
      "title": "Primary Cement Rig Days",
      "type": "variable",
      "value": "0.3 0.4 0.5"
  },
  {
      "module_id": 3,
      "id": 305,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_cbl",
      "title": "Cement Bond Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 3,
      "id": 306,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_csq",
      "title": "Cement Squeeze Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 3,
      "id": 307,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_cmt2",
      "title": "2nd Stage Cement Rig Days",
      "type": "variable",
      "value": "0.3 0.4 0.5"
  },
  {
      "module_id": 3,
      "id": 308,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_side",
      "title": "Sidetrack Rig Days",
      "type": "variable",
      "value": "40 80 120"
  },
  {
      "module_id": 3,
      "id": 309,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_wo",
      "title": "Workover Rig Days",
      "type": "variable",
      "value": "2.5 5 7.5"
  },
  {
      "module_id": 3,
      "id": 310,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "csh_d_aban",
      "title": "Abandonment Rig Days",
      "type": "variable",
      "value": "1 2 3"
  },
  {
      "module_id": 3,
      "id": 311,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_wab",
      "title": "Welltec Elements Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 3,
      "id": 312,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_und",
      "title": "Underreaming Probability",
      "type": "variable",
      "value": "0.3"
  },
  {
      "module_id": 3,
      "id": 313,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_cal",
      "title": "Caliber Log Probability",
      "type": "variable",
      "value": "0.4"
  },
  {
      "module_id": 3,
      "id": 314,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_cmt",
      "title": "Primary Cement Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 3,
      "id": 315,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_cbl",
      "title": "Cement Bond Log Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 3,
      "id": 316,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_csq",
      "title": "Cement Squeeze Probability",
      "type": "variable",
      "value": "0"
  },
  {
      "module_id": 3,
      "id": 317,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_cmt2",
      "title": "2nd Stage Cement Probability",
      "type": "variable",
      "value": ".1"
  },
  {
      "module_id": 3,
      "id": 318,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_side",
      "title": "Sidetrack Probability",
      "type": "variable",
      "value": "0"
  },
  {
      "module_id": 3,
      "id": 319,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_wo",
      "title": "Workover Probability",
      "type": "variable",
      "value": ".2"
  },
  {
      "module_id": 3,
      "id": 320,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "csh_x_aban",
      "title": "Abandonment Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 3,
      "id": 321,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_wab",
      "title": "Welltec Elements (USD)",
      "type": "variable",
      "value": "wab+csh_d_wab*rig"
  },
  {
      "module_id": 3,
      "id": 322,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_und",
      "title": "Underreaming (USD)",
      "type": "variable",
      "value": "und+csh_d_und*rig"
  },
  {
      "module_id": 3,
      "id": 323,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_cal",
      "title": "Caliber Log (USD)",
      "type": "variable",
      "value": "cal+csh_d_cal*rig"
  },
  {
      "module_id": 3,
      "id": 324,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_cmt",
      "title": "Primary Cement (USD)",
      "type": "variable",
      "value": "cmt+csh_d_cmt*rig"
  },
  {
      "module_id": 3,
      "id": 325,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_cbl",
      "title": "Cement Bond Log (USD)",
      "type": "variable",
      "value": "cbl+csh_d_cbl*rig"
  },
  {
      "module_id": 3,
      "id": 326,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_csq",
      "title": "Cement Squeeze (USD)",
      "type": "variable",
      "value": "csq+csh_d_csq*rig"
  },
  {
      "module_id": 3,
      "id": 327,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_cmt2",
      "title": "2nd Stage Cement (USD)",
      "type": "variable",
      "value": "cmt2+csh_d_cmt2*rig"
  },
  {
      "module_id": 3,
      "id": 328,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_side",
      "title": "Sidetrack (USD)",
      "type": "variable",
      "value": "side+csh_d_side*rig"
  },
  {
      "module_id": 3,
      "id": 329,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_wo",
      "title": "Workover (USD)",
      "type": "variable",
      "value": "wo+csh_d_wo*rig"
  },
  {
      "module_id": 3,
      "id": 330,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "csh_tot_aban",
      "title": "Abandonment (USD)",
      "type": "variable",
      "value": "aban+csh_d_aban*rig"
  },
  {
      "module_id": 3,
      "id": 350,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cshwab_all",
      "title": "Cased Hole Wab (USD)",
      "type": "variable",
      "value": "csh_tot_wab*csh_x_wab+csh_tot_und*csh_x_und+csh_tot_cal*csh_x_cal+csh_tot_cmt*csh_x_cmt+csh_tot_cbl*csh_x_cbl+csh_tot_csq*csh_x_csq+csh_tot_cmt2*csh_x_cmt2+csh_tot_side*csh_x_side+csh_tot_wo*csh_x_wo+csh_tot_aban*csh_x_aban"
  },
  {
      "module_id": 4,
      "id": 401,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_wab",
      "title": "Welltec Elements Rig Days",
      "type": "variable",
      "value": ".1 .2 .3"
  },
  {
      "module_id": 4,
      "id": 402,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_und",
      "title": "Underreaming Rig Days",
      "type": "variable",
      "value": "0.25 0.5 0.75"
  },
  {
      "module_id": 4,
      "id": 403,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_cal",
      "title": "Caliber Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 4,
      "id": 404,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_cmt",
      "title": "Primary Cement Rig Days",
      "type": "variable",
      "value": "1 2 3"
  },
  {
      "module_id": 4,
      "id": 405,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_cbl",
      "title": "Cement Bond Log Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 4,
      "id": 406,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_csq",
      "title": "Cement Squeeze Rig Days",
      "type": "variable",
      "value": "0.5 1 1.5"
  },
  {
      "module_id": 4,
      "id": 407,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_cmt2",
      "title": "2nd Stage Cement Rig Days",
      "type": "variable",
      "value": "1 2 3"
  },
  {
      "module_id": 4,
      "id": 408,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_side",
      "title": "Sidetrack Rig Days",
      "type": "variable",
      "value": "40 80 120"
  },
  {
      "module_id": 4,
      "id": 409,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_wo",
      "title": "Workover Rig Days",
      "type": "variable",
      "value": "10 15 20"
  },
  {
      "module_id": 4,
      "id": 410,
      "correlation": "",
      "factor": "",
      "method": "pert",
      "name": "ref_d_aban",
      "title": "Abandonment Rig Days",
      "type": "variable",
      "value": "3 4 5"
  },
  {
      "module_id": 4,
      "id": 411,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_wab",
      "title": "Welltec Elements Probability",
      "type": "variable",
      "value": "0"
  },
  {
      "module_id": 4,
      "id": 412,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_und",
      "title": "Underreaming Probability",
      "type": "variable",
      "value": "0.6"
  },
  {
      "module_id": 4,
      "id": 413,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_cal",
      "title": "Caliber Log Probability",
      "type": "variable",
      "value": "0.8"
  },
  {
      "module_id": 4,
      "id": 414,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_cmt",
      "title": "Primary Cement Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 4,
      "id": 415,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_cbl",
      "title": "Cement Bond Log Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 4,
      "id": 416,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_csq",
      "title": "Cement Squeeze Probability",
      "type": "variable",
      "value": ".4"
  },
  {
      "module_id": 4,
      "id": 417,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_cmt2",
      "title": "2nd Stage Cement Probability",
      "type": "variable",
      "value": ".3"
  },
  {
      "module_id": 4,
      "id": 418,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_side",
      "title": "Sidetrack Probability",
      "type": "variable",
      "value": "0.1"
  },
  {
      "module_id": 4,
      "id": 419,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_wo",
      "title": "Workover Probability",
      "type": "variable",
      "value": ".4"
  },
  {
      "module_id": 4,
      "id": 420,
      "correlation": "",
      "factor": "",
      "method": "bernoulli",
      "name": "ref_x_aban",
      "title": "Abandonment Probability",
      "type": "variable",
      "value": "1"
  },
  {
      "module_id": 4,
      "id": 421,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_wab",
      "title": "Welltec Elements (USD)",
      "type": "variable",
      "value": "wab+ref_d_wab*rig"
  },
  {
      "module_id": 4,
      "id": 422,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_und",
      "title": "Underreaming (USD)",
      "type": "variable",
      "value": "und+ref_d_und*rig"
  },
  {
      "module_id": 4,
      "id": 423,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_cal",
      "title": "Caliber Log (USD)",
      "type": "variable",
      "value": "cal+ref_d_cal*rig"
  },
  {
      "module_id": 4,
      "id": 424,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_cmt",
      "title": "Primary Cement (USD)",
      "type": "variable",
      "value": "cmt+ref_d_cmt*rig"
  },
  {
      "module_id": 4,
      "id": 425,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_cbl",
      "title": "Cement Bond Log (USD)",
      "type": "variable",
      "value": "cbl+ref_d_cbl*rig"
  },
  {
      "module_id": 4,
      "id": 426,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_csq",
      "title": "Cement Squeeze (USD)",
      "type": "variable",
      "value": "csq+ref_d_csq*rig"
  },
  {
      "module_id": 4,
      "id": 427,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_cmt2",
      "title": "2nd Stage Cement (USD)",
      "type": "variable",
      "value": "cmt2+ref_d_cmt2*rig"
  },
  {
      "module_id": 4,
      "id": 428,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_side",
      "title": "Sidetrack (USD)",
      "type": "variable",
      "value": "side+ref_d_side*rig"
  },
  {
      "module_id": 4,
      "id": 429,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_wo",
      "title": "Workover (USD)",
      "type": "variable",
      "value": "wo+ref_d_wo*rig"
  },
  {
      "module_id": 4,
      "id": 430,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_tot_aban",
      "title": "Abandonment (USD)",
      "type": "variable",
      "value": "aban+ref_d_aban*rig"
  },
  {
      "module_id": 4,
      "id": 450,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "ref_all",
      "title": "Reference Case (USD)",
      "type": "variable",
      "value": "ref_tot_wab*ref_x_wab+ref_tot_und*ref_x_und+ref_tot_cal*ref_x_cal+ref_tot_cmt*ref_x_cmt+ref_tot_cbl*ref_x_cbl+ref_tot_csq*ref_x_csq+ref_tot_cmt2*ref_x_cmt2+ref_tot_side*ref_x_side+ref_tot_wo*ref_x_wo+ref_tot_aban*ref_x_aban"
  },
  {
      "module_id": 5,
      "id": 501,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cmp_ophwab_tot",
      "title": "Open Hole WAB (USD)",
      "type": "variable",
      "value": "ophwab_all"
  },
  {
      "module_id": 5,
      "id": 502,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cmp_cshwab_tot",
      "title": "Cased Hole WAB (USD)",
      "type": "variable",
      "value": "cshwab_all"
  },
  {
      "module_id": 5,
      "id": 503,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cmp_ref_tot",
      "title": "Reference Case (USD)",
      "type": "variable",
      "value": "ref_all"
  },
  {
      "module_id": 5,
      "id": 504,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "dif_oph_csh_tot",
      "title": "Dif Open Hole - Cased Hole WAB",
      "type": "variable",
      "value": "ophwab_all - cshwab_all"
  },
  {
      "module_id": 5,
      "id": 505,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cmp_ref_tot",
      "title": "Dif Reference Case - Open Hole WAB",
      "type": "variable",
      "value": "ref_all - ophwab_all"
  },
  {
      "module_id": 5,
      "id": 506,
      "correlation": "",
      "factor": "",
      "method": "function",
      "name": "cmp_ref_tot",
      "title": "Dif Reference Case - Cased Hole WAB",
      "type": "variable",
      "value": "ref_all - cshwab_all"
  }
]
